services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres_db
    env_file: ".env.yml"
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5332:5432" # Expose PostgreSQL on port 5332
    restart: unless-stopped

  # Spring API
  spring-api:
    container_name: spring-boot-backend
    build:
      context: ./medical # Path to the backend Dockerfile
      dockerfile: Dockerfile
    env_file: ".env.yml"
    ports:
      - "8080:8080"
    depends_on:
      - postgres # Ensure PostgreSQL starts before Spring Boot
    restart: unless-stopped

  # React Frontend
  react-ui:
    container_name: react-frontend
    build:
      context: ./react # Path to the frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  postgres_data:
